# Generated by Django 5.0.2 on 2024-05-11 13:10

import apps.university.models
import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='universities/', verbose_name='Фото')),
                ('name', models.CharField(max_length=400, verbose_name='Название Университета')),
                ('rectors_first_name', models.CharField(max_length=400, verbose_name='ИМЯ Ректора')),
                ('rectors_second_name', models.CharField(max_length=400, verbose_name='ФАМИЛИЯ Ректора')),
                ('rectors_middle_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='ОТЧЕСТВО Ректора')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='Аббревиатура')),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'db_table': 'universities_tab',
                'ordering': ['id', 'name', 'city'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UniversityDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=300, verbose_name='Название документа')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на документ')),
                ('document_file', models.FileField(upload_to=apps.university.models.document_upload_path, verbose_name='Файл документа')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='university.university')),
            ],
            options={
                'verbose_name': 'Документ Университета',
                'verbose_name_plural': 'Документы Университета',
                'db_table': 'university_docs_tab',
                'managed': True,
            },
        ),
    ]
