# Generated by Django 5.0.2 on 2024-04-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('delivery_info', models.TextField(blank=True, null=True, verbose_name='Политика доставки')),
                ('terms_of_payment', models.TextField(blank=True, null=True, verbose_name='Условия платежа')),
                ('mbank', models.BooleanField(default=False, verbose_name='Метод Платежа (MBANK)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поитика Оплаты Аканута',
                'verbose_name_plural': 'Поитика Оплаты Аканутов',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
