# Generated by Django 5.0.2 on 2024-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('OTHER', 'Дугое'), ('NONE', 'Не указан')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='tik_tok_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='ТикТок'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Твиттер'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ютуб'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CORD', 'Координатор'), ('MEMR', 'Участники'), ('MANG', 'Менеджер'), ('CAPT', 'Капитан'), ('ADVS', 'Эдвайзер'), ('ALUM', 'Аламник')], default='MEMR', max_length=50),
        ),
        migrations.AlterModelTable(
            name='resetpasword',
            table='codes_res_password_table',
        ),
        migrations.AlterModelTable(
            name='user',
            table='main_table',
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
    ]
