# Generated by Django 5.0.2 on 2024-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_facebook_url_user_gender_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('OTHER', 'Дугое'), ('NONE', 'Не указан')], default='NONE', max_length=50, verbose_name='Пол'),
        ),
    ]
