# Generated by Django 5.0.2 on 2024-05-11 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamproject_image'),
        ('users', '0009_alter_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CORD', 'Координатор'), ('MEMR', 'Участники'), ('MANG', 'Менеджер'), ('CAPT', 'Капитан'), ('ADVS', 'Эдвайзер'), ('ALUM', 'Аламник')], default='ALUM', max_length=255, verbose_name='Роль')),
                ('department', models.CharField(blank=True, choices=[('IT', 'ИТ'), ('HR', 'HR'), ('FIN', 'Финансы'), ('MKT', 'Маркетинг'), ('PRD', 'Продукты'), ('SALES', 'Продажи'), ('FIN', 'Финансы'), ('SMM', 'SMM'), ('OTHER', 'Другое')], default='SMM', max_length=255, null=True, verbose_name='Отдел')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий проект')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teamproject', verbose_name='Проект')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='teams.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность Пользователя',
                'verbose_name_plural': 'Активности Ползователей',
                'db_table': 'activities_table',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
    ]
