# Generated by Django 5.0.2 on 2024-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamproject_image'),
        ('users', '0010_useractivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivities',
            name='project',
        ),
        migrations.AddField(
            model_name='useractivities',
            name='project',
            field=models.ManyToManyField(to='teams.teamproject', verbose_name='Проект'),
        ),
    ]
