# Generated by Django 4.1.7 on 2024-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_useractivities_project_useractivities_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departament',
            field=models.CharField(blank=True, choices=[('IT', 'ИТ'), ('HR', 'HR'), ('FIN', 'Финансы'), ('MKT', 'Маркетинг'), ('PRD', 'Продукты'), ('SALES', 'Продажи'), ('FIN', 'Финансы'), ('SMM', 'SMM'), ('OTHER', 'Другое')], max_length=300, null=True, verbose_name='Отдел'),
        ),
    ]
