# Generated by Django 4.1.7 on 2024-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notifications',
            field=models.BooleanField(default=False, verbose_name='Отправлять уведомления'),
        ),
    ]
