# Generated by Django 5.0.2 on 2024-05-11 13:10

import apps.teams.models
import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Инстаграм')),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Твиттер')),
                ('tik_tok_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='ТикТок')),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Фейсбук')),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ютуб')),
                ('telegram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Телеграм')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='teams/', verbose_name='Фото')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата основания')),
                ('name', models.CharField(max_length=400, verbose_name='Название команды')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('university', models.CharField(blank=True, max_length=200, null=True, verbose_name='Университет команды')),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Миссия')),
                ('goals', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Цели')),
                ('tasks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задачи')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('phone_two', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон 2')),
                ('phone_three', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон 3')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название Проекта')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий проект')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('count_of_beneficiaries', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Количество бенефициаров')),
                ('budget', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Бюджет')),
                ('income', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Прибыль')),
                ('investments', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Инвестиции')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('problem', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Проблема')),
                ('decision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Решение')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
            ],
            options={
                'verbose_name': 'Проект Команды',
                'verbose_name_plural': 'Проекты Команд',
                'db_table': 'projects_tab',
                'ordering': ['id', 'name', 'city'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamProjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=300, verbose_name='Название документа')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на документ')),
                ('document_file', models.FileField(upload_to=apps.teams.models.document_upload_path, verbose_name='Файл документа')),
                ('team_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.teamproject')),
            ],
            options={
                'verbose_name': 'Документ Проекта',
                'verbose_name_plural': 'Документы Проектов',
                'db_table': 'projetc_docs_tab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamProjectPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='team_project_photos/', verbose_name='Фото')),
                ('team_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='teams.teamproject')),
            ],
            options={
                'verbose_name': 'Фото Проекта',
                'verbose_name_plural': 'Фото Проектов',
                'db_table': 'project_photos_tab',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
