# Generated by Django 5.0.2 on 2024-05-11 13:22

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='team_projects_images/', verbose_name='Фото'),
        ),
    ]
