# Generated by Django 5.0.2 on 2024-05-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('first_name', models.CharField(max_length=300, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('role', models.CharField(choices=[('CORD', 'Координатор'), ('MEMR', 'Участники'), ('MANG', 'Менеджер'), ('CAPT', 'Капитан'), ('ADVS', 'Эдвайзер'), ('ALUM', 'Аламник')], max_length=300, verbose_name='Роль')),
                ('departament', models.CharField(choices=[('IT', 'ИТ'), ('HR', 'HR'), ('FIN', 'Финансы'), ('MKT', 'Маркетинг'), ('PRD', 'Продукты'), ('SALES', 'Продажи'), ('FIN', 'Финансы'), ('SMM', 'SMM'), ('OTHER', 'Другое')], max_length=300, verbose_name='Отдел')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team')),
            ],
            options={
                'verbose_name': 'Приглашение в команду',
                'verbose_name_plural': 'Приглашения в команды',
                'db_table': 'invitation_to_members_tab',
                'managed': True,
            },
        ),
    ]
