# Generated by Django 5.0.2 on 2024-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_invitationtomembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtomembers',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
