# Generated by Django 5.0.2 on 2024-05-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_invitationtomembers_invited_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtomembers',
            options={'managed': True, 'ordering': ['id', 'status'], 'verbose_name': 'Приглашение в команду', 'verbose_name_plural': 'Приглашения в команды'},
        ),
    ]
