# Generated by Django 4.1.7 on 2024-05-13 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_invitationtomembers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtomembers',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен'),
        ),
    ]
