# Generated by Django 4.1.7 on 2024-05-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_invitationtomembers_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='team_documents/')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на документ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.team')),
            ],
            options={
                'verbose_name': 'Документ Команды',
                'verbose_name_plural': 'Документы Команды',
                'db_table': 'docs_tab',
                'ordering': ['-id', '-created_at'],
                'managed': True,
            },
        ),
    ]
