# Generated by Django 4.1.7 on 2024-05-13 11:02

import apps.teams.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_teamdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdocuments',
            name='name',
            field=models.CharField(default=1, max_length=300, verbose_name='Название документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamdocuments',
            name='document_file',
            field=models.FileField(default=1, upload_to=apps.teams.models.team_document_upload_path, verbose_name='Файл документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamdocuments',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.team', verbose_name='Команада'),
        ),
    ]
