# Generated by Django 4.1.7 on 2024-05-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Команда'),
        ),
    ]
