# Generated by Django 4.1.7 on 2024-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_alter_teammembers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
