# Generated by Django 4.1.7 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_teammembers_company_teammembers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='departament',
            field=models.CharField(blank=True, choices=[('IT', 'ИТ'), ('HR', 'HR'), ('FIN', 'Финансы'), ('MKT', 'Маркетинг'), ('PRD', 'Продукты'), ('SALES', 'Продажи'), ('FIN', 'Финансы'), ('SMM', 'SMM'), ('OTHER', 'Другое')], max_length=255, null=True, verbose_name='Отдел'),
        ),
    ]
