# Generated by Django 5.0.2 on 2024-04-08 05:24

import apps.chat.models
import django_resized.forms
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='идентификационный ключ')),
                ('name', models.CharField(max_length=150, verbose_name='название комнаты')),
            ],
            options={
                'verbose_name': 'комната чата',
                'verbose_name_plural': 'комната чатов',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_online', models.BooleanField(default=False, verbose_name='В сети')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='имя пользователя')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='chat_avatars/', verbose_name='аватарка')),
            ],
            options={
                'verbose_name': 'пользователь чата',
                'verbose_name_plural': 'пользователи чата',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('body', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to=apps.chat.models.message_photo_upload_path, verbose_name='фото')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chat.models.message_file_upload_path, verbose_name='файл')),
                ('type', models.CharField(choices=[('simple', 'Обычный'), ('announcement', 'Объявление')], default='simple', max_length=50, verbose_name='тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('send_notification', models.BooleanField(default=False, verbose_name='Отправить уведомление о сообщений')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщении',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestForSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('header', models.CharField(max_length=255, verbose_name='тема заявки')),
                ('name', models.CharField(max_length=255, verbose_name='имя и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='ваш контактный e-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='ваш контактный телефон')),
                ('content', models.CharField(max_length=2000, verbose_name='текст заявки')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chat.models.request_for_support_upload_path, verbose_name='файл')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('accepted', 'Принято'), ('closed', 'Закрыто')], default='waiting', max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'заявка на тех. поддержку',
                'verbose_name_plural': 'заявки на тех. поддержку',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
