# Generated by Django 4.1.7 on 2024-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group_general', 'Групповая общая'), ('personal', 'Личная')], default='personal', max_length=50, verbose_name='тип комнаты'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='type',
            field=models.CharField(default='private', max_length=100, verbose_name='тип комнаты'),
        ),
    ]
