# Generated by Django 4.1.7 on 2024-05-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_room_type_chatroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_groups', to='chat.chatuser'),
        ),
    ]
