# Generated by Django 4.1.7 on 2024-05-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='type',
        ),
    ]
