# Generated by Django 4.1.7 on 2024-05-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='chat.chatroom', verbose_name='комната'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_groups', to='chat.chatuser', verbose_name='пользователь'),
        ),
    ]
